### ISSUE TITLE
GO version crash

### ISSUE THREAD

**Issue by drom** [drom/animal#11]
Building GO version:

```bash
cd go
go version
# go version go1.6.3 linux/amd64
go build animal.go data.go types.go
```

Running the test:

```
./animal < ../test/test.txt
```

Getting Error:
```
Play 'Guess the Animal'
Think of an animal and the computer will try to guess it...
Are you thinking of an animal?
Does it swim?
Is it a Fish?
What was the animal you were thinking of?
Please type in a Yes/No question that would distinguish an elephant from a Fish
What is the answer to your question for an elephant
Please answer yes or no.
What is the answer to your question for an elephant
Are you thinking of an animal?
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0x4e98e0, 0xc82000a230)
        /usr/lib64/go/src/runtime/panic.go:481 +0x3e6
main.main()
        /home/drom/work/github/drom/animal/go/animal.go:19 +0x434
```

CC: @beforan

**Comment by beforan** [comment]
@drom looks like 2 things at play here:

the `test.txt` is missing a valid answer. it never provides the answer to the `elephant` question `big`.
It goes straight on to enter `l`, which by my understanding is not valid (`y`/`n` expected).

the go version gracefully handles this by looping around, but that results in `test.txt` then passing `n` which was intended for later, to exit the program.

go accepts the `n` input, then starts over with "Are you thinking of an animal", at which point there is no more content to the `test.txt` file.

The second issue, then, is that not entering anything crashes the go program. It gracefully handles incorrect inputs, but expects input length to be at least 1 (hence bounds out of range).

**Comment by beforan** [comment]
I guess the next question is does the `test.txt` need amending, or does the go version' behaviour need amending because I've misunderstood something? does `test.txt` work correctly for the other implementations?

I'll fix the empty input bug regardless.

**Comment by drom** [comment]
@beforan `l` is the valid answer in the original game and in the other version of the game. `l` == `LIST` you have to print current database in JSON format.
